#!/bin/bash

set -e -u -x

version="$(cat version/version)"

git config --global user.email "ci@localhost"
git config --global user.name "CI Bot"

git clone ./grafana-release ./finalized-repo

pushd finalized-repo
  set +x
  echo "$BOSH_PRIVATE_CONFIG" > config/private.yml
  set -x

  bosh create-release --final --name grafana --version "$version"
  git add -A
  git commit -m "release v${version}"
  git tag -f "v${version}"
popd